config/routes.rb
Rails.application.routes.draw do
  root to: 'admins#index'
  # create user
  resources :user, only: %i[destroy]
  get '/sign_up', to: 'users#new'
  post '/sign_up', to: 'users#create'

  # user authentication
  get    '/sign_in', to: 'sessions#new'
  post   '/sign_in', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :admins

  # api
  namespace :api do
    resources :provide_feeds, only: %i[index create show destroy]
    # user authentication
    post '/sign_in', to: 'sessions#create'
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_secure_token

  # validations
  validates_presence_of :name, :email, :password
  validates_length_of :name, minimum: 5, maximum: 20
  validates_length_of :email, minimum: 5, maximum: 20
  validates_length_of :password, minimum: 5, maximum: 20

end

app/controllers/users_controller.rb
# users  class
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to root_url
    elsif
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

  # todo create validate class
  # todo validate email
  # todo validate password max min length
  # todo add columns unique true

  def validate_name
    return false if user_params[:name].present?
  end

  def validate_email
    return false if user_params[:email].present?
  end

  def validate_password
    return false if user_params[:password].present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<h1>sigin in</h1>

<%= form_for(@user, url: sign_up_path) do |f| %>
  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  <% end %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit "sign up" %>
<% end %>